version: "3"
services:

  rabbit:
    image: rabbitmq:3.10.7-management
    container_name: rabbit
    restart: always
    ports:
      - 15672:15672   # смотреть что происходит в браузере 
      - 5672:5672     # AMQP порт
    expose:
      - 5672
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - rabbit

networks:
  rabbit:
    driver: bridge